MVCWebApp/Models/Courses.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models
{
    public class Courses
    {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string CourseDescription { get; set; }

        public string CourseImageURL { get; set; }
        public string CourseVideoURL { get; set; }
        public string  CourseTutor  { get; set; }
        public string CourseFees { get; set; }
        public DateTime CreatedDate { get; set; }

      

    }
}

MVCWebApp/Models/Dept.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models
{
    public class Dept
    {

        public int DeptNo { get; set; }
        public string DName { get; set; }
        public string Loc { get; set; }
    }

    public class  Employee
    {

        public int EmployeeID { get; set; }
        public string EmpName { get; set; }
        public string Salary { get; set; }
    }

    public class Organization
    {
        public List<Dept> dep = new List<Dept>();
        public List<Employee> emp = new List<Employee>();

    }
}

MVCWebApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCWebApp.Models;

namespace MVCWebApp.Controllers
{
    public class CourseController : Controller
    {
        static List<Courses> course;

        public ViewResult Create()
        {

            return View();
        }
       
        public ViewResult ListOfCourses()
        {
            //Courses crs = new Courses();
            //crs.ListOfCourse();
            return View(ListOfCourse());
        }
        [HttpPost]
        public ViewResult Create(Courses C)
        {
          course = ListOfCourse();
            course.Add(C);
            return View("ListOfCourses", course);
        }

        public  List<Courses> ListOfCourse()
        {
            List<Courses> course = new List<Courses>();
            course.Add(new Courses { CourseID = 1, CourseName = "ASP.NET", CourseDescription = "Agility training given by Nagaraju sir", CourseFees = "10000", CourseTutor = "Nagaraju sir", CreatedDate = DateTime.Now });
            course.Add(new Courses { CourseID = 2, CourseName = "MVC ", CourseDescription = "Agility training given by Nagaraju sir", CourseFees = "20000", CourseTutor = "Nagaraju sir", CreatedDate = DateTime.Now });
            course.Add(new Courses { CourseID = 3, CourseName = "MVC Core", CourseDescription = "Agility training given by Nagaraju sir", CourseFees = "15000", CourseTutor = "Nagaraju sir", CreatedDate = DateTime.Now });
            course.Add(new Courses { CourseID = 4, CourseName = "Angular 2", CourseDescription = "Agility training given by Nagaraju sir", CourseFees = "70000", CourseTutor = "Nagaraju sir", CreatedDate = DateTime.Now });
            course.Add(new Courses { CourseID = 5, CourseName = "CSS", CourseDescription = "Agility training given by Nagaraju sir", CourseFees = "20000", CourseTutor = "Nagaraju sir", CreatedDate = DateTime.Now });
            course.Add(new Courses { CourseID = 6, CourseName = "HTML5", CourseDescription = "Agility training given by Nagaraju sir", CourseFees = "10600", CourseTutor = "Nagaraju sir", CreatedDate = DateTime.Now });
            course.Add(new Courses { CourseID = 7, CourseName = "WEB API", CourseDescription = "Agility training given by Nagaraju sir", CourseFees = "10070", CourseTutor = "Nagaraju sir", CreatedDate = DateTime.Now });
            course.Add(new Courses { CourseID = 8, CourseName = "Entity FW", CourseDescription = "Agility training given by Nagaraju sir", CourseFees = "14000", CourseTutor = "Nagaraju sir", CreatedDate = DateTime.Now });
            course.Add(new Courses { CourseID = 9, CourseName = "Identity FW", CourseDescription = "Agility training given by Nagaraju sir", CourseFees = "10900", CourseTutor = "Nagaraju sir", CreatedDate = DateTime.Now });
            return course;
        }
    }
}

MVCWebApp/Controllers/F1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MVCWebApp.Controllers
{
    public class F1Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public string GetMessage()///Not preferered
        {
            return "c";
        }
        public ContentResult GetContent()//preferred
        {
            return Content("<h1>welcome</h1>","text/html");
        }

        public VirtualFileResult GetProject()
        {
            return File("/Downloads/WEB-API FAQ.docx","Application/docx","d.docx");
        }

        public ViewResult Display()
        {
            return View();
        }
        public ViewResult Help()
        {
            //return View("Display");
            return View("~/Views/Home/About.cshtml");
        }
    }
   
}

MVCWebApp/Controllers/F2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCWebApp.Models;
using System.Dynamic;

namespace MVCWebApp.Controllers
{
    public class F2Controller : Controller
    {
        public IActionResult Index()
        {
            ViewBag.MTitle = "Learning";
            ViewBag.Subtitle = "aa";
            return View();
        }
        public ViewResult ListDepartments()
        {
            return View(GetDepartments());
        }
        private List<Dept> GetDepartments()
        {
            List<Dept> depts = new List<Dept>() {
            new Dept() { DeptNo=10,DName="Sales",Loc="North"},
            new Dept() { DeptNo = 11, DName = "Sales", Loc = "North" },
            new Dept() { DeptNo = 12, DName = "Sales", Loc = "North" }
            };
            return depts;


        }
        [HttpGet]
        public ViewResult AddDept()
        {
            return View();
        }
        [HttpPost]
        public ViewResult AddDept(int DeptNo, string DeptName, string Loc)
        {
            List<Dept> dept = GetDepartments();
            dept.Add(new Dept() { DeptNo = DeptNo, DName = DeptName, Loc = Loc });
            return View("ListDepartments", dept);
        }

        public List<Employee> GetEmployee()
        {
            List<Employee> emp = new List<Employee>();

            emp.Add(new Employee { EmployeeID = 1, EmpName = "Apurv", Salary = "50000" });
            emp.Add(new Employee { EmployeeID = 1, EmpName = "Koustav", Salary = "50000" });
            emp.Add(new Employee { EmployeeID = 2, EmpName = "Vivek", Salary = "50000" });

            emp.Add(new Employee { EmployeeID = 3, EmpName = "Sandeep", Salary = "50000" });
            emp.Add(new Employee { EmployeeID = 4, EmpName = "Balaji", Salary = "50000" });
            return emp;

        }
        public ViewResult ListOfEmployees()
        {
            return View(GetEmployee());
        }

        //public class ViewModel
        //{
        //    public IEnumerable<Employee> Employee { get; set; }
        //    public IEnumerable<Dept> Dept { get; set; }
        //}
        public ActionResult IndexViewModel()
        {
            //ViewBag.Message = "two models in same view";
            //ViewModel myModel = new ViewModel();
            //myModel.Employee = GetEmployee();
            //myModel.Dept = GetDepartments();
            //return View(myModel);
            //Organization org = new Organization();
            //org.dep = GetDepartments();
            //org.emp = GetEmployee();
            //return View(org);

            dynamic myModel = new ExpandoObject();
            myModel.dept = GetDepartments();
            myModel.Empl = GetEmployee();
            return View(myModel);
        }

    }
}

MVCWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MVCWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

MVCWebApp/Views/Course/Create.cshtml
@model MVCWebApp.Models.Courses

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Courses</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="CourseID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CourseID" class="form-control" />
                <span asp-validation-for="CourseID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CourseName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CourseName" class="form-control" />
                <span asp-validation-for="CourseName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CourseDescription" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CourseDescription" class="form-control" />
                <span asp-validation-for="CourseDescription" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CourseImageURL" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CourseImageURL" class="form-control" />
                <span asp-validation-for="CourseImageURL" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CourseVideoURL" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CourseVideoURL" class="form-control" />
                <span asp-validation-for="CourseVideoURL" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CourseTutor" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CourseTutor" class="form-control" />
                <span asp-validation-for="CourseTutor" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CourseFees" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CourseFees" class="form-control" />
                <span asp-validation-for="CourseFees" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CreatedDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CreatedDate" class="form-control" type="datetime-local" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCWebApp/Views/Course/ListOfCourses.cshtml
@model IEnumerable<MVCWebApp.Models.Courses>

@{
    ViewData["Title"] = "ListOfCourses";
}

<h2>ListOfCourses</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CourseID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CourseName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CourseDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CourseImageURL)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CourseVideoURL)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CourseTutor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CourseFees)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedDate)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseImageURL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseVideoURL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseTutor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseFees)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

MVCWebApp/Views/F1/Display.cshtml
@{
    ViewData["Title"] = "Display";
}

<h2>Display</h2>

MVCWebApp/Views/F2/AddDept.cshtml
@{
    ViewData["Title"] = "AddDept";
}

<h2>AddDept</h2>



@using (Html.BeginForm())
{
    <div>
        DeptNo
        @Html.TextBox("DeptNo")

        DeptName
        @Html.TextBox("DeptName")

        Loc
        @Html.TextBox("Loc")

        <input type="submit" name="name" value="AddDept" />
        </div>
        <div>
        @Html.ActionLink("List", "ListDepartments")
        </div>
}

MVCWebApp/Views/F2/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<h1>@ViewBag.MTitle</h1>
<h1>@ViewBag.Subtitle</h1>

MVCWebApp/Views/F2/IndexViewModel.cshtml
@model dynamic
@using MVCWebApp.Models;

<h1>List of Departments</h1>

<table border="1">
    <tr>
        <th>Dept No</th>
        <th>Dept Name</th>
        <th>Loc</th>
    </tr>
 @foreach (var item in Model.dept)
 {
        <tr>
            <td>@item.DeptNo</td>
            <td>@item.DName</td>
            <td>@item.Loc</td>
        </tr>
    }
</table>
<div>
    @Html.ActionLink("Add Departments", "AddDept")
</div>

<h1>Employee List List</h1>

<table border="1">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Salary</th>
      
    </tr>
    @foreach (var emp in Model.Empl)
    {
        <tr>
            <td>@emp.EmployeeID</td>
            <td>@emp.EmpName</td>
            <td>@emp.Salary</td>
           
        </tr>
    }
</table>
  

MVCWebApp/Views/F2/ListDepartments.cshtml
@model List<MVCWebApp.Models.Dept>

@{
    ViewData["Title"] = "ListDepartments";
}

<h2>ListDepartments</h2>
@using (Html.BeginForm())
{
@foreach (var item in Model)
{
    <div>
        <li>Dept No:@item.DeptNo DeptName:@item.DName Loc:@item.Loc</li>
    </div>

}<br />
    <br />
    <div>
        @Html.ActionLink("Add Departments", "AddDept")
    </div>
}

MVCWebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MVCWebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

MVCWebApp/Views/Shared/View.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

MVCWebApp/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCWebApp</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Training</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Course" asp-action="Create">Create Courses</a></li>
                    <li><a asp-area="" asp-controller="Course" asp-action="AddDept">Add Dept</a></li>
                    <li><a asp-area="" asp-controller="F2" asp-action="IndexViewModel">2 Models in 1 view</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - MVCWebApp</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>